/*
 The implied super() call in Bottom2’s constructor cannot be satisfied
because there is no no-arg constructor in Top. A default, no-arg constructor is generated by
the compiler only if the class has no constructor defined explicitly
*/

class Top {

    // Top() {}

    public Top(String s) {
        System.out.print("B");
    }
}

public class Bottom2 extends Top {
    public Bottom2(String s) {
        System.out.print("D");
    }

    public static void main(String[] args) {
        new Bottom2("C"); // supe()
        System.out.print(" ");
    }
}
